version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean package
  post_build:
    commands:
      - echo Build completed successfully
      - dir target
artifacts:
  files:
    - target/my-app-1.0-SNAPSHOT.jar
  discard-paths: yes
